{{- include "interview-app.validateTUMID" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-db
  namespace: {{ include "interview-app.namespace" . }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: interview-db-selector
  template:
    metadata:
      labels:
        app: interview-db-selector
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.name | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: {{ .Values.database.service.targetPort }}
          {{- with .Values.database.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
