{{- include "interview-app.validateTUMID" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "interview-app.fullname" . }}-db-pvc
  namespace: {{ include "interview-app.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storageSize | default "1Gi" }}
