{{- include "interview-app.validateTUMID" . -}}
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ include "interview-app.namespace" . }}
spec:
  selector:
    app: interview-db-selector
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
      protocol: TCP
  type: ClusterIP
