{{- include "interview-app.validateTUMID" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-server
  namespace: {{ include "interview-app.namespace" . }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: interview-server-selector
  template:
    metadata:
      labels:
        app: interview-server-selector
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          image: "{{ include "interview-app.imageRepository" (list . "server") }}:{{ .Values.server.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy | default .Values.image.pullPolicy }}
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          env:
            {{- range .Values.server.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            - name: SERVER_PORT
              value: {{ .Values.server.service.targetPort | quote }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: password
            - name: GENAI_SERVICE_URL
              value: {{ .Values.genai.serviceUrl | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-client
  namespace: {{ include "interview-app.namespace" . }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: interview-client-selector
  template:
    metadata:
      labels:
        app: interview-client-selector
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: client
          image: "{{ include "interview-app.imageRepository" (list . "client") }}:{{ .Values.client.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy | default .Values.image.pullPolicy }}
          {{- with .Values.client.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.client.service.targetPort }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: client-nginx-config
