apiVersion: v1
kind: Service
metadata:
  name: genai
  labels:
    {{- include "interview-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai
spec:
  type: {{ .Values.genai.service.type }}
  ports:
    - port: {{ .Values.genai.service.port }}
      targetPort: {{ .Values.genai.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "interview-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: genai
