{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  selector:
    app: grafana
  ports:
    - name: http
      port: {{ .Values.monitoring.grafana.service.port }}
      targetPort: {{ .Values.monitoring.grafana.service.targetPort }}
{{- end }}