{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: {{ .Values.monitoring.prometheus.service.type }}
  selector:
    app: prometheus
  ports:
    - name: http
      port: {{ .Values.monitoring.prometheus.service.port }}
      targetPort: {{ .Values.monitoring.prometheus.service.targetPort }}
{{- end }}