apiVersion: v1
kind: Secret
metadata:
  name: ai-mock-interview-secret
  namespace: ai-mock-interview
type: Opaque
data:
  openai-api-key: {{ .Values.server.openaiApiKey | default "placeholder-value" | b64enc | quote }}
