apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: ai-mock-interview
spec:
  selector:
    app: interview-client-selector
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
  type: {{ .Values.client.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: ai-mock-interview
spec:
  selector:
    app: interview-server-selector
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
  type: {{ .Values.server.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: ai-mock-interview
spec:
  selector:
    app: interview-server-selector
  ports:
    - port: 8080
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
  type: ClusterIP
